import {
  Activity,
  AlertCircle,
  BadgeCheck,
  BarChart3,
  BedDouble,
  Bell,
  CalendarClock,
  CheckSquare,
  ClipboardList,
  CreditCard,
  FileText,
  FlaskConical,
  FormInput,
  Hospital,
  IdCard,
  ImageUp,
  Layers3,
  ListFilter,
  Loader2,
  Menu,
  MousePointerClick,
  Package,
  Pill,
  Settings,
  SquareMousePointer,
  Table2,
  Text,
  Wand2,
} from "lucide-react";

import type { BundleCategory, BundleItem, BundleSection } from "@/features/bundle/bundle-types";

function section(title: string, description: string, examples: string[]): BundleSection {
  return { title, description, examples };
}

export const bundleItems: BundleItem[] = [
  {
    id: "buttons",
    label: "Buttons",
    title: "Buttons",
    description: "Action buttons for forms, tables, modals, uploads, print, export, and workflow commands.",
    category: "Foundation",
    icon: MousePointerClick,
    count: 16,
    keywords: ["primary", "secondary", "save", "cancel", "print", "export", "upload", "loading"],
    sections: [
      section("Core variants", "Primary, secondary, outline, ghost, danger, disabled, and icon-only commands.", ["Primary", "Secondary", "Outline", "Ghost", "Danger", "Disabled", "Icon button"]),
      section("Healthcare actions", "Common hospital workflow buttons used in OPD, IPD, billing, pharmacy, and diagnostics.", ["Add patient", "Save workflow", "Cancel visit", "Print bill", "Export report", "Upload file", "Mark ready"]),
      section("Sizes and states", "Small, medium, large, loading, and full-width mobile actions.", ["Small", "Medium", "Large", "Loading", "Full width"]),
    ],
    usage: `<Button>Save workflow</Button>\n<Button variant="outline">Cancel</Button>\n<Button variant="danger">Delete</Button>`,
  },
  {
    id: "forms",
    label: "Forms",
    title: "Forms",
    description: "Reusable healthcare/admin form layouts with validation, helper text, and responsive columns.",
    category: "Foundation",
    icon: ClipboardList,
    count: 10,
    keywords: ["patient registration", "doctor profile", "appointment", "billing", "lab", "pharmacy", "validation"],
    sections: [
      section("Layout patterns", "Single column, two column, and three column forms for admin dashboards.", ["Basic form", "Two column form", "Three column form"]),
      section("Healthcare forms", "Ready patterns for hospital workflows.", ["Patient registration", "Doctor profile", "Appointment booking", "Billing form", "Pharmacy item", "Lab test"]),
      section("Validation UI", "Required fields, helper text, error text, and disabled fields.", ["Required indicator", "Error message", "Helper text", "Disabled field"]),
    ],
    usage: `<FormField label="Patient name" required error="Patient name is required">\n  <Input placeholder="Enter patient name" />\n</FormField>`,
  },
  {
    id: "inputs",
    label: "Inputs",
    title: "Inputs",
    description: "Text, number, email, password, textarea, select, checkbox, radio, toggle, search, and icon inputs.",
    category: "Foundation",
    icon: FormInput,
    count: 16,
    keywords: ["text", "number", "email", "password", "phone", "textarea", "select", "checkbox", "radio", "toggle"],
    sections: [
      section("Basic fields", "Common input fields for forms and filters.", ["Text", "Number", "Email", "Password", "Phone", "Textarea", "Select"]),
      section("Choice controls", "Selection and boolean controls.", ["Multi-select UI", "Checkbox", "Radio", "Toggle switch"]),
      section("Advanced states", "Search, icon, prefix/suffix, disabled, error, and success fields.", ["Search input", "Input with icon", "Prefix/suffix", "Disabled", "Error", "Success"]),
    ],
    usage: `<Input placeholder="Search patient, UHID, mobile..." />`,
  },
  {
    id: "cards",
    label: "Cards",
    title: "Cards",
    description: "Soft dashboard cards for summaries, patients, doctors, appointments, stock, lab reports, and actions.",
    category: "Data Display",
    icon: SquareMousePointer,
    count: 11,
    keywords: ["stats", "patient", "doctor", "appointment", "pharmacy", "lab", "billing", "alert"],
    sections: [
      section("Core cards", "General containers and dashboard cards.", ["Basic card", "Stats card", "Revenue card", "Hover card", "Action card"]),
      section("Hospital cards", "Entity-specific cards used across modules.", ["Patient card", "Doctor card", "Appointment card", "Lab report card"]),
      section("Operational cards", "Pharmacy, billing, and alert summaries.", ["Pharmacy stock card", "Billing summary card", "Alert card"]),
    ],
    usage: `<Card><CardHeader><CardTitle>Pending orders</CardTitle></CardHeader><CardContent>...</CardContent></Card>`,
  },
  {
    id: "tables",
    label: "Tables",
    title: "Tables",
    description: "Responsive data tables for patient, doctor, appointment, invoice, pharmacy, and lab lists.",
    category: "Data Display",
    icon: Table2,
    count: 14,
    keywords: ["basic", "striped", "bordered", "compact", "patient list", "pagination", "actions"],
    sections: [
      section("Table styles", "Standard table patterns for dense admin data.", ["Basic", "Striped", "Bordered", "Compact"]),
      section("Healthcare tables", "Domain-specific worklists.", ["Patient list", "Doctor list", "Appointment list", "Billing invoice", "Pharmacy stock", "Lab test"]),
      section("Table tools", "Search, filters, badges, action dropdown, and pagination.", ["Search", "Filters", "Status badges", "Action menu", "Pagination"]),
    ],
    usage: `<DataTable data={patients} columns={columns} />`,
  },
  {
    id: "modals",
    label: "Modals",
    title: "Modals",
    description: "Centered dialogs and drawer style panels for confirmations, forms, payments, and print previews.",
    category: "Feedback",
    icon: Layers3,
    count: 9,
    keywords: ["small", "medium", "large", "confirmation", "delete", "form", "payment", "drawer"],
    sections: [
      section("Dialog sizes", "Small, medium, and large centered modal patterns.", ["Small", "Medium", "Large"]),
      section("Workflow modals", "Reusable confirmation and transaction dialogs.", ["Confirmation", "Delete", "Form modal", "Payment modal", "Print preview"]),
      section("Side panel", "Drawer-style details for patient and order workflows.", ["Drawer style modal"]),
    ],
    usage: `<Dialog.Root><Dialog.Content>Confirm discharge?</Dialog.Content></Dialog.Root>`,
  },
  {
    id: "tabs",
    label: "Tabs",
    title: "Tabs",
    description: "Horizontal and vertical tab patterns for profiles, billing, pharmacy, lab reports, and dashboards.",
    category: "Foundation",
    icon: Layers3,
    count: 8,
    keywords: ["basic", "underline", "card", "patient profile", "billing", "pharmacy", "lab", "vertical"],
    sections: [
      section("Tab styles", "Basic, underline, card, and vertical tabs.", ["Basic tabs", "Underline tabs", "Card tabs", "Vertical tabs"]),
      section("Healthcare tabs", "Real screen tab patterns.", ["Patient profile", "Billing", "Pharmacy", "Lab report"]),
    ],
    usage: `<Tabs defaultValue="overview"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger></TabsList></Tabs>`,
  },
  {
    id: "badges",
    label: "Badges & Status",
    title: "Badges & Status",
    description: "Status badges for clinical, billing, pharmacy, lab, and operational states.",
    category: "Feedback",
    icon: BadgeCheck,
    count: 15,
    keywords: ["active", "pending", "paid", "critical", "low stock", "emergency"],
    sections: [
      section("Workflow states", "Common approval and completion labels.", ["Active", "Inactive", "Pending", "Approved", "Rejected", "Completed", "Cancelled"]),
      section("Finance states", "Billing and payment statuses.", ["Paid", "Unpaid", "Partial"]),
      section("Clinical risk", "Priority, stock, and emergency states.", ["Critical", "Low stock", "Normal", "High priority", "Emergency"]),
    ],
    usage: `<Badge tone="success">Paid</Badge>\n<StatusPill tone="critical">Critical</StatusPill>`,
  },
  {
    id: "alerts",
    label: "Alerts & Toasts",
    title: "Alerts & Toasts",
    description: "Inline alerts and toast examples for validation, notifications, success, warning, and errors.",
    category: "Feedback",
    icon: Bell,
    count: 8,
    keywords: ["success", "error", "warning", "info", "dismissible", "toast", "validation", "system"],
    sections: [
      section("Alert tones", "Common inline feedback panels.", ["Success", "Error", "Warning", "Info", "Dismissible"]),
      section("Toast actions", "Short feedback after save, export, upload, or failure.", ["Save success", "Export ready", "Upload failed"]),
    ],
    usage: `<AlertBanner icon={AlertCircle} title="Payment pending" tone="warning">Clear bill before dispense.</AlertBanner>`,
  },
  {
    id: "dropdowns",
    label: "Dropdowns",
    title: "Dropdowns",
    description: "Action menus and profile/filter dropdowns for tables and dashboards.",
    category: "Foundation",
    icon: Menu,
    count: 6,
    keywords: ["basic", "action", "profile", "filter", "multi action", "three-dot"],
    sections: [
      section("Menu patterns", "Reusable dropdown menu patterns.", ["Basic dropdown", "Action dropdown", "Profile dropdown", "Filter dropdown"]),
      section("Table actions", "Dense menus used inside worklists.", ["Multi action menu", "Three-dot table action menu"]),
    ],
    usage: `<ActionDropdown actions={['View', 'Edit', 'Print']} />`,
  },
  {
    id: "date-time",
    label: "Date & Time Pickers",
    title: "Date & Time Pickers",
    description: "Date and time selection UI for appointments, DOB, follow-ups, and reports.",
    category: "Foundation",
    icon: CalendarClock,
    count: 6,
    keywords: ["date", "time", "range", "appointment", "dob", "follow-up"],
    sections: [
      section("Picker examples", "Native-friendly picker layouts.", ["Date picker", "Time picker", "Date range picker"]),
      section("Hospital flows", "Common healthcare date/time scenarios.", ["Appointment selector", "DOB selector", "Follow-up date selector"]),
    ],
    usage: `<Input type="date" />\n<Input type="time" />`,
  },
  {
    id: "search-filters",
    label: "Search & Filters",
    title: "Search & Filters",
    description: "Global search, table search, advanced filters, status filters, and applied chips.",
    category: "Foundation",
    icon: ListFilter,
    count: 9,
    keywords: ["global search", "table search", "advanced filter", "status", "department", "doctor", "chips"],
    sections: [
      section("Search patterns", "Search bars for global and table-level discovery.", ["Global search", "Table search"]),
      section("Filter controls", "Department, doctor, date range, and status filter combinations.", ["Advanced filter panel", "Status filter", "Department filter", "Doctor filter", "Date range filter"]),
      section("Filter actions", "Reset button and applied filter chips.", ["Reset filter", "Applied chips"]),
    ],
    usage: `<Input placeholder="Search patient, UHID, doctor..." />`,
  },
  {
    id: "charts",
    label: "Charts & Graphs",
    title: "Charts & Graphs",
    description: "Recharts examples for hospital dashboards, revenue, visits, pharmacy, lab, and billing trends.",
    category: "Data Display",
    icon: BarChart3,
    count: 10,
    keywords: ["line", "bar", "pie", "donut", "area", "revenue", "visits", "pharmacy", "lab"],
    sections: [
      section("Chart types", "Common dashboard visualizations.", ["Line chart", "Bar chart", "Pie chart", "Donut chart", "Area chart"]),
      section("Healthcare analytics", "Hospital metrics and trends.", ["Revenue trend", "Patient visits", "Appointment status", "Pharmacy sales", "Lab test volume", "Billing collection"]),
    ],
    usage: `<ResponsiveContainer><BarChart data={data}>...</BarChart></ResponsiveContainer>`,
  },
  {
    id: "dashboard-widgets",
    label: "Dashboard Widgets",
    title: "Dashboard Widgets",
    description: "KPI, activity, appointment, revenue, stock, report, and quick action widgets.",
    category: "Data Display",
    icon: Activity,
    count: 9,
    keywords: ["kpi", "mini chart", "activity", "appointment", "revenue", "department", "stock", "reports"],
    sections: [
      section("Executive widgets", "High-level cards for dashboards.", ["KPI cards", "Mini chart card", "Revenue summary", "Department performance"]),
      section("Operational widgets", "Daily work cards for staff.", ["Recent activity", "Upcoming appointments", "Low stock", "Pending reports", "Quick actions"]),
    ],
    usage: `<StatCard label="Appointments" value={128} change="+12%" context="Today" tone="success" icon={Activity} />`,
  },
  {
    id: "patient-components",
    label: "Patient UI Components",
    title: "Patient UI Components",
    description: "Patient profile, vitals, visit history, prescriptions, allergies, timeline, and documents.",
    category: "Healthcare",
    icon: IdCard,
    count: 9,
    keywords: ["patient", "profile", "vitals", "visit", "history", "prescription", "allergy", "timeline"],
    sections: [
      section("Patient profile", "Reusable blocks for 360-degree patient views.", ["Patient profile header", "Patient summary card", "Vitals card", "Medical history block"]),
      section("Patient records", "Clinical and document widgets.", ["Visit history", "Prescription summary", "Allergies warning", "Appointment timeline", "Document list"]),
    ],
    usage: `<PatientSummaryCard patient={patient} />`,
  },
  {
    id: "hospital-components",
    label: "Hospital UI Components",
    title: "Hospital UI Components",
    description: "Department, ward, bed, doctor availability, emergency queue, occupancy, and branch widgets.",
    category: "Healthcare",
    icon: Hospital,
    count: 7,
    keywords: ["department", "ward", "bed", "doctor", "staff", "emergency", "occupancy", "branch"],
    sections: [
      section("Hospital operations", "Reusable operational blocks.", ["Department card", "Ward/bed status", "Doctor availability", "Staff attendance"]),
      section("Command widgets", "Monitoring widgets for live hospital flow.", ["Emergency queue", "Room occupancy", "Hospital branch selector"]),
    ],
    usage: `<DepartmentCard department="Cardiology" occupancy={82} />`,
  },
  {
    id: "billing-components",
    label: "Billing UI Components",
    title: "Billing UI Components",
    description: "Invoice, payment status, amount breakdown, tax, discount, receipt, and due alert UI.",
    category: "Healthcare",
    icon: CreditCard,
    count: 8,
    keywords: ["invoice", "payment", "amount", "tax", "discount", "receipt", "due"],
    sections: [
      section("Billing blocks", "Finance components for hospital billing screens.", ["Invoice summary", "Payment status badge", "Amount breakdown", "Tax summary"]),
      section("Payment workflow", "Payment and receipt UI.", ["Discount/extra charges row", "Payment method selector", "Receipt preview", "Due payment alert"]),
    ],
    usage: `<InvoiceSummary total={12400} paid={8000} due={4400} />`,
  },
  {
    id: "pharmacy-components",
    label: "Pharmacy UI Components",
    title: "Pharmacy UI Components",
    description: "Medicine, stock, expiry, batch, prescription row, sales cart, and low stock alert UI.",
    category: "Healthcare",
    icon: Pill,
    count: 7,
    keywords: ["medicine", "stock", "expiry", "batch", "prescription", "sales cart", "low stock"],
    sections: [
      section("Medicine components", "Pharmacy UI blocks for orders and inventory.", ["Medicine card", "Stock status badge", "Batch details", "Prescription medicine row"]),
      section("Pharmacy alerts", "Risk and sales widgets.", ["Expiry warning card", "Sales cart UI", "Low stock alert"]),
    ],
    usage: `<MedicineCard medicine={medicine} />`,
  },
  {
    id: "lab-components",
    label: "Lab/Diagnostics UI Components",
    title: "Lab/Diagnostics UI Components",
    description: "Lab test, sample collection, result rows, critical alerts, report preview, and doctor review UI.",
    category: "Healthcare",
    icon: FlaskConical,
    count: 7,
    keywords: ["lab", "diagnostics", "sample", "result", "critical", "report", "doctor review"],
    sections: [
      section("Lab workflow", "Diagnostic process components.", ["Lab test card", "Report status badge", "Sample collection card", "Test result row"]),
      section("Clinical review", "Report and critical result UI.", ["Critical value alert", "Report preview", "Doctor review panel"]),
    ],
    usage: `<LabTestCard test="CBC" status="Sample Collected" />`,
  },
  {
    id: "empty-loaders",
    label: "Empty States & Loaders",
    title: "Empty States & Loaders",
    description: "Empty, no result, loading, skeleton, button loader, form skeleton, and table skeleton states.",
    category: "Feedback",
    icon: Loader2,
    count: 8,
    keywords: ["empty", "no result", "loader", "skeleton", "button loader", "table skeleton", "form skeleton"],
    sections: [
      section("Empty states", "No data, no search result, and empty table panels.", ["Empty table", "No search result", "No data"]),
      section("Loading states", "Page, button, card, table, and form loading patterns.", ["Page loader", "Button loader", "Card skeleton", "Table skeleton", "Form skeleton"]),
    ],
    usage: `<EmptyState icon={SearchX} title="No records found" description="Try another filter." />`,
  },
  {
    id: "timeline",
    label: "Timeline & Activity Logs",
    title: "Timeline & Activity Logs",
    description: "Patient journey, appointment, billing, lab, pharmacy, and audit timeline components.",
    category: "Workflow",
    icon: Activity,
    count: 6,
    keywords: ["timeline", "activity", "patient journey", "appointment", "billing", "lab", "pharmacy", "audit"],
    sections: [
      section("Clinical timelines", "Journey and diagnostic workflow timelines.", ["Patient journey", "Appointment activity", "Lab sample timeline"]),
      section("Operational logs", "Billing, pharmacy, and user audit activity.", ["Billing activity", "Pharmacy sales timeline", "User audit log"]),
    ],
    usage: `<TimelineItem title="Sample collected" time="10:20 AM" />`,
  },
  {
    id: "file-upload",
    label: "File Upload Components",
    title: "File Upload Components",
    description: "Drag/drop, single, multiple, image, PDF, progress, uploaded file list, and error states.",
    category: "Workflow",
    icon: ImageUp,
    count: 8,
    keywords: ["upload", "drag", "drop", "image", "pdf", "progress", "file list", "error"],
    sections: [
      section("Upload controls", "Common file upload blocks.", ["Drag and drop", "Single file", "Multiple file", "Image preview", "PDF upload card"]),
      section("Upload states", "Progress and error display.", ["Progress upload bar", "Uploaded file list", "Error file state"]),
    ],
    usage: `<FileUpload accept="application/pdf,image/*" multiple />`,
  },
  {
    id: "stepper",
    label: "Stepper / Wizard Forms",
    title: "Stepper / Wizard Forms",
    description: "Multi-step flows for patient registration, appointment, billing, and lab orders.",
    category: "Workflow",
    icon: Wand2,
    count: 6,
    keywords: ["stepper", "wizard", "registration", "appointment", "billing", "lab", "completed"],
    sections: [
      section("Stepper states", "Completed, active, and pending state design.", ["Basic stepper", "Completed", "Active", "Pending"]),
      section("Wizard flows", "Hospital multi-step process examples.", ["Patient registration", "Appointment booking", "Billing wizard", "Lab test order"]),
    ],
    usage: `<Stepper steps={steps} currentStep={2} />`,
  },
  {
    id: "settings-ui",
    label: "Settings UI",
    title: "Settings UI",
    description: "Profile, hospital, notification, security, theme, role permission, and toggle settings.",
    category: "Settings",
    icon: Settings,
    count: 7,
    keywords: ["profile", "hospital", "notification", "security", "theme", "role", "permission", "toggle"],
    sections: [
      section("Settings forms", "Admin configuration screens.", ["Profile settings", "Hospital settings", "Security settings", "Theme settings"]),
      section("Permission controls", "Role and toggle based settings rows.", ["Notification settings", "Role permission UI", "Toggle settings rows"]),
    ],
    usage: `<SettingsRow title="SMS alerts" description="Send token updates" enabled />`,
  },
  {
    id: "typography-icons",
    label: "Typography & Icons",
    title: "Typography & Icons",
    description: "Headings, paragraphs, labels, helper text, errors, links, icon buttons, and healthcare/admin icons.",
    category: "Foundation",
    icon: Text,
    count: 9,
    keywords: ["heading", "paragraph", "label", "helper", "error", "link", "icons", "healthcare", "admin"],
    sections: [
      section("Typography", "Text hierarchy for dashboards and forms.", ["Headings", "Paragraphs", "Labels", "Helper text", "Error text", "Links"]),
      section("Icon usage", "Icon buttons and healthcare/admin icon examples.", ["Icon button", "Healthcare icons", "Admin dashboard icons"]),
    ],
    usage: `<h2 className="text-lg font-semibold text-foreground">Patient overview</h2>`,
  },
];

export const bundleCategories: BundleCategory[] = ["Foundation", "Data Display", "Feedback", "Healthcare", "Workflow", "Settings"];

export const bundleAliases: Record<string, string> = {
  button: "buttons",
  textbox: "inputs",
  textarea: "inputs",
  "search-box": "search-filters",
  "form-controls": "forms",
  navbar: "hospital-components",
  sidebar: "hospital-components",
  box: "cards",
  "alert-status": "badges",
  drawer: "modals",
  toast: "alerts",
  table: "tables",
  "empty-loading": "empty-loaders",
};

export function normalizeBundleId(itemId?: string) {
  if (!itemId) return undefined;
  return bundleAliases[itemId] ?? itemId;
}

export function getBundleItem(itemId?: string) {
  const normalized = normalizeBundleId(itemId);
  return bundleItems.find((item) => item.id === normalized);
}
