import type { Role } from "@/types";
import type { BottleneckMetric, JourneyEvent, PatientJourneyRecord, PatientJourneyStage, RadiologyJourneyOrder, RadiologyModality, RadiologyOrderStatus, RadiologyPriority, RadiologySource, ServiceToken, ServiceTokenStatus, ServiceWorkOrder, SplitWorkflowConfig, SplitWorkflowKey, SplitWorkflowPriority, SmartAlert, TrackerBoard } from "@/features/patient-journey/patient-journey-types";

export const patientJourneyRoles: Role[] = [
  "Super Admin",
  "Hospital Admin",
  "Doctor",
  "Nurse",
  "Receptionist",
  "Lab Technician",
  "Radiologist",
  "Pharmacist",
  "Billing Executive",
  "Management",
];

export const journeyStages: PatientJourneyStage[] = [
  "Registered",
  "Waiting Doctor",
  "In Consultation",
  "Lab Pending",
  "Radiology Pending",
  "Report Ready",
  "Billing Pending",
  "Pharmacy Pending",
  "Admission Suggested",
  "Discharge Pending",
  "Completed",
];

export const mockJourneyPatients: PatientJourneyRecord[] = [
  {
    id: "pj-001",
    visitId: "visit-240530-001",
    token: "OPD-024",
    patientName: "Aisha Khan",
    uhid: "PLH-240221",
    ageGender: "12 / Female",
    phone: "98******21",
    visitType: "OPD",
    department: "Pediatrics",
    doctor: "Dr. Neha Malik",
    stage: "Waiting Doctor",
    location: "OPD Waiting Area",
    waitingMinutes: 38,
    totalMinutes: 52,
    priority: "Pediatric",
    status: "Delayed",
    billingStatus: "Paid",
    labStatus: "Not ordered",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Pending",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Wheeze and cough review",
    vitals: "SpO2 98%, Pulse 92/min",
    allergy: "Seasonal allergy",
    nextAction: "Call patient to Room 2",
    blocker: "Doctor queue running 18 min late",
    ownerRole: "Doctor",
  },
  {
    id: "pj-002",
    visitId: "visit-240530-002",
    token: "ER-006",
    patientName: "Unknown Emergency",
    uhid: "UNK-2026-0098",
    ageGender: "35 / Unknown",
    phone: "Not available",
    visitType: "Emergency",
    department: "Emergency",
    doctor: "Emergency Team",
    stage: "Radiology Pending",
    location: "Trauma Bay 1",
    waitingMinutes: 7,
    totalMinutes: 34,
    priority: "Critical",
    status: "Critical",
    billingStatus: "Emergency hold",
    labStatus: "STAT processing",
    radiologyStatus: "CT pending",
    pharmacyStatus: "Crash cart issued",
    insuranceStatus: "Unknown",
    dischargeStatus: "Transfer review",
    chiefComplaint: "Road traffic accident",
    vitals: "BP 118/76, SpO2 96%",
    allergy: "Unknown",
    nextAction: "Start CT scan and assign ICU bed",
    blocker: "CT room occupied by STAT case",
    ownerRole: "Nurse",
  },
  {
    id: "pj-003",
    visitId: "visit-240530-003",
    token: "OPD-030",
    patientName: "Arjun Kapoor",
    uhid: "PLH-240076",
    ageGender: "58 / Male",
    phone: "98******76",
    visitType: "Follow-up",
    department: "Orthopedics",
    doctor: "Dr. Aman Verma",
    stage: "Billing Pending",
    location: "Billing Counter 2",
    waitingMinutes: 24,
    totalMinutes: 96,
    priority: "Senior Citizen",
    status: "Approaching delay",
    billingStatus: "Insurance query",
    labStatus: "Report ready",
    radiologyStatus: "X-Ray approved",
    pharmacyStatus: "Not started",
    insuranceStatus: "Query raised",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Post fracture review",
    vitals: "BP 132/82, Pulse 84/min",
    allergy: "None recorded",
    nextAction: "Resolve TPA query",
    blocker: "Implant item approval pending",
    ownerRole: "Billing Executive",
  },
  {
    id: "pj-004",
    visitId: "visit-240530-004",
    token: "IPD-014",
    patientName: "Meera Joshi",
    uhid: "PLH-240188",
    ageGender: "42 / Female",
    phone: "97******88",
    visitType: "IPD",
    department: "Medicine",
    doctor: "Dr. Karan Shah",
    stage: "Discharge Pending",
    location: "Ward B / Bed 12",
    waitingMinutes: 145,
    totalMinutes: 2810,
    priority: "Normal",
    status: "Delayed",
    billingStatus: "Final bill pending",
    labStatus: "Clear",
    radiologyStatus: "Clear",
    pharmacyStatus: "Return pending",
    insuranceStatus: "Approved",
    dischargeStatus: "Billing blocked",
    chiefComplaint: "Fever observation, clinically stable",
    vitals: "Temp 36.9 C, BP 120/78",
    allergy: "Penicillin",
    nextAction: "Escalate final billing",
    blocker: "Final bill not cleared",
    ownerRole: "Billing Executive",
  },
  {
    id: "pj-005",
    visitId: "visit-240530-005",
    token: "OPD-031",
    patientName: "Rahul Mehta",
    uhid: "PLH-240310",
    ageGender: "31 / Male",
    phone: "99******10",
    visitType: "OPD",
    department: "ENT",
    doctor: "Dr. Sana Rao",
    stage: "Pharmacy Pending",
    location: "Pharmacy Queue",
    waitingMinutes: 16,
    totalMinutes: 74,
    priority: "Normal",
    status: "Normal",
    billingStatus: "Paid",
    labStatus: "Not ordered",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Stock check",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Ear pain and congestion",
    vitals: "Stable",
    allergy: "None recorded",
    nextAction: "Dispense prescription",
    ownerRole: "Pharmacist",
  },
  {
    id: "pj-006",
    visitId: "visit-240530-006",
    token: "LAB-018",
    patientName: "Sofia D'Souza",
    uhid: "PLH-240402",
    ageGender: "27 / Female",
    phone: "96******02",
    visitType: "OPD",
    department: "Obstetrics",
    doctor: "Dr. Ira Sen",
    stage: "Lab Pending",
    location: "Sample Collection",
    waitingMinutes: 62,
    totalMinutes: 88,
    priority: "Pregnancy",
    status: "Delayed",
    billingStatus: "Paid",
    labStatus: "Sample pending",
    radiologyStatus: "USG scheduled",
    pharmacyStatus: "Not started",
    insuranceStatus: "Corporate",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Antenatal review",
    vitals: "BP 118/74, Pulse 82/min",
    allergy: "None recorded",
    nextAction: "Collect antenatal panel sample",
    blocker: "Collection bay overloaded",
    ownerRole: "Lab Technician",
  },
  {
    id: "pj-007",
    visitId: "visit-240530-007",
    token: "OPD-032",
    patientName: "Kabir Singh",
    uhid: "PLH-240415",
    ageGender: "46 / Male",
    phone: "98******15",
    visitType: "OPD",
    department: "Cardiology",
    doctor: "Dr. Rohan Mehta",
    stage: "In Consultation",
    location: "Consultation Room 4",
    waitingMinutes: 5,
    totalMinutes: 44,
    priority: "Urgent",
    status: "Normal",
    billingStatus: "Paid",
    labStatus: "ECG ordered",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Not started",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Chest discomfort review",
    vitals: "BP 146/90, Pulse 98/min",
    allergy: "None recorded",
    nextAction: "Complete consultation and order ECG",
    ownerRole: "Doctor",
  },
  {
    id: "pj-008",
    visitId: "visit-240530-008",
    token: "RAD-011",
    patientName: "Nandini Rao",
    uhid: "PLH-240516",
    ageGender: "64 / Female",
    phone: "97******16",
    visitType: "OPD",
    department: "Neurology",
    doctor: "Dr. Vikas Sethi",
    stage: "Radiology Pending",
    location: "MRI Waiting",
    waitingMinutes: 49,
    totalMinutes: 121,
    priority: "Senior Citizen",
    status: "Delayed",
    billingStatus: "Paid",
    labStatus: "Clear",
    radiologyStatus: "MRI scheduled",
    pharmacyStatus: "Not started",
    insuranceStatus: "Corporate",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Headache and dizziness",
    vitals: "BP 138/84, SpO2 97%",
    allergy: "Sulfa",
    nextAction: "Start MRI scan",
    blocker: "MRI slot delayed",
    ownerRole: "Radiologist",
  },
  {
    id: "pj-009",
    visitId: "visit-240530-009",
    token: "IPD-021",
    patientName: "Fatima Sheikh",
    uhid: "PLH-240623",
    ageGender: "71 / Female",
    phone: "95******23",
    visitType: "IPD",
    department: "ICU",
    doctor: "Dr. Karan Shah",
    stage: "Admission Suggested",
    location: "Emergency Hold Bay",
    waitingMinutes: 31,
    totalMinutes: 76,
    priority: "Critical",
    status: "Critical",
    billingStatus: "Emergency hold",
    labStatus: "Critical value",
    radiologyStatus: "CT approved",
    pharmacyStatus: "Medication due",
    insuranceStatus: "Eligibility pending",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Sepsis observation",
    vitals: "BP 92/60, Pulse 118/min",
    allergy: "Unknown",
    nextAction: "Allocate ICU bed",
    blocker: "ICU bed confirmation pending",
    ownerRole: "Nurse",
  },
  {
    id: "pj-010",
    visitId: "visit-240530-010",
    token: "OT-004",
    patientName: "Dev Patel",
    uhid: "PLH-240712",
    ageGender: "39 / Male",
    phone: "94******12",
    visitType: "IPD",
    department: "Surgery",
    doctor: "Dr. Priya Nair",
    stage: "In Consultation",
    location: "Pre-op Holding",
    waitingMinutes: 22,
    totalMinutes: 640,
    priority: "Normal",
    status: "Approaching delay",
    billingStatus: "Package active",
    labStatus: "Pre-op labs complete",
    radiologyStatus: "Clear",
    pharmacyStatus: "OT medicines reserved",
    insuranceStatus: "Approved",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Planned laparoscopic procedure",
    vitals: "Stable",
    allergy: "Latex",
    nextAction: "Complete anesthesia clearance",
    blocker: "Consent witness pending",
    ownerRole: "Doctor",
  },
  {
    id: "pj-011",
    visitId: "visit-240530-011",
    token: "BILL-017",
    patientName: "Ishaan Verma",
    uhid: "PLH-240818",
    ageGender: "8 / Male",
    phone: "93******18",
    visitType: "OPD",
    department: "Pediatrics",
    doctor: "Dr. Neha Malik",
    stage: "Billing Pending",
    location: "Billing Counter 1",
    waitingMinutes: 12,
    totalMinutes: 58,
    priority: "Pediatric",
    status: "Normal",
    billingStatus: "Discount approval",
    labStatus: "Not ordered",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Not started",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Fever and throat pain",
    vitals: "Temp 38.2 C",
    allergy: "None recorded",
    nextAction: "Approve discount and collect payment",
    ownerRole: "Billing Executive",
  },
  {
    id: "pj-012",
    visitId: "visit-240530-012",
    token: "PHR-022",
    patientName: "Leela Menon",
    uhid: "PLH-240927",
    ageGender: "53 / Female",
    phone: "92******27",
    visitType: "Follow-up",
    department: "Endocrinology",
    doctor: "Dr. Ira Sen",
    stage: "Pharmacy Pending",
    location: "Pharmacy Window 3",
    waitingMinutes: 33,
    totalMinutes: 101,
    priority: "Normal",
    status: "Delayed",
    billingStatus: "Paid",
    labStatus: "HbA1c report ready",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Partial stock",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Diabetes follow-up",
    vitals: "BP 126/80",
    allergy: "None recorded",
    nextAction: "Suggest substitute medicine",
    blocker: "Metformin XR low stock",
    ownerRole: "Pharmacist",
  },
  {
    id: "pj-013",
    visitId: "visit-240530-013",
    token: "ER-009",
    patientName: "Police Case Unknown",
    uhid: "UNK-2026-0101",
    ageGender: "28 / Male",
    phone: "Not available",
    visitType: "Emergency",
    department: "Emergency",
    doctor: "Emergency Team",
    stage: "Lab Pending",
    location: "Casualty Bed 3",
    waitingMinutes: 14,
    totalMinutes: 39,
    priority: "Critical",
    status: "Critical",
    billingStatus: "Emergency hold",
    labStatus: "STAT sample pending",
    radiologyStatus: "X-Ray ordered",
    pharmacyStatus: "Issued",
    insuranceStatus: "Unknown",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Assault injury",
    vitals: "BP 110/70, Pulse 104/min",
    allergy: "Unknown",
    nextAction: "Collect STAT trauma panel",
    blocker: "Identity confirmation pending",
    ownerRole: "Lab Technician",
  },
  {
    id: "pj-014",
    visitId: "visit-240530-014",
    token: "OPD-041",
    patientName: "Tara Gill",
    uhid: "PLH-241033",
    ageGender: "34 / Female",
    phone: "91******33",
    visitType: "OPD",
    department: "Dermatology",
    doctor: "Dr. Sana Rao",
    stage: "Completed",
    location: "Exit",
    waitingMinutes: 0,
    totalMinutes: 62,
    priority: "Normal",
    status: "Normal",
    billingStatus: "Paid",
    labStatus: "Not ordered",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Dispensed",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Skin rash",
    vitals: "Stable",
    allergy: "Dust",
    nextAction: "Follow-up after 7 days",
    ownerRole: "Receptionist",
  },
  {
    id: "pj-015",
    visitId: "visit-240530-015",
    token: "IPD-026",
    patientName: "Mohan Prasad",
    uhid: "PLH-241144",
    ageGender: "67 / Male",
    phone: "90******44",
    visitType: "IPD",
    department: "Nephrology",
    doctor: "Dr. Vikas Sethi",
    stage: "Discharge Pending",
    location: "Renal Ward / Bed 8",
    waitingMinutes: 188,
    totalMinutes: 3920,
    priority: "Senior Citizen",
    status: "Delayed",
    billingStatus: "Final bill pending",
    labStatus: "Clear",
    radiologyStatus: "Clear",
    pharmacyStatus: "Return complete",
    insuranceStatus: "Query raised",
    dischargeStatus: "Insurance blocked",
    chiefComplaint: "Dialysis admission closure",
    vitals: "BP 134/82",
    allergy: "None recorded",
    nextAction: "Resolve TPA discharge query",
    blocker: "Insurance discharge clearance pending",
    ownerRole: "Billing Executive",
  },
  {
    id: "pj-016",
    visitId: "visit-240530-016",
    token: "RAD-018",
    patientName: "Rhea Sharma",
    uhid: "PLH-241251",
    ageGender: "24 / Female",
    phone: "89******51",
    visitType: "OPD",
    department: "Orthopedics",
    doctor: "Dr. Aman Verma",
    stage: "Report Ready",
    location: "Doctor Review Queue",
    waitingMinutes: 9,
    totalMinutes: 87,
    priority: "Normal",
    status: "Normal",
    billingStatus: "Paid",
    labStatus: "Not ordered",
    radiologyStatus: "X-Ray approved",
    pharmacyStatus: "Not started",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Ankle sprain",
    vitals: "Stable",
    allergy: "None recorded",
    nextAction: "Doctor review of X-Ray",
    ownerRole: "Doctor",
  },
  {
    id: "pj-017",
    visitId: "visit-240530-017",
    token: "OPD-047",
    patientName: "Omar Ali",
    uhid: "PLH-241362",
    ageGender: "45 / Male",
    phone: "88******62",
    visitType: "Follow-up",
    department: "Pulmonology",
    doctor: "Dr. Rohan Mehta",
    stage: "Waiting Doctor",
    location: "OPD Waiting Area",
    waitingMinutes: 27,
    totalMinutes: 33,
    priority: "Disabled",
    status: "Approaching delay",
    billingStatus: "Paid",
    labStatus: "PFT pending",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Not started",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "COPD follow-up",
    vitals: "SpO2 94%",
    allergy: "None recorded",
    nextAction: "Priority call to consultation",
    ownerRole: "Doctor",
  },
  {
    id: "pj-018",
    visitId: "visit-240530-018",
    token: "LAB-026",
    patientName: "Priyanka Bose",
    uhid: "PLH-241478",
    ageGender: "29 / Female",
    phone: "87******78",
    visitType: "OPD",
    department: "General Medicine",
    doctor: "Dr. Karan Shah",
    stage: "Lab Pending",
    location: "Lab Processing",
    waitingMinutes: 72,
    totalMinutes: 116,
    priority: "Normal",
    status: "Delayed",
    billingStatus: "Paid",
    labStatus: "Processing delayed",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Not started",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Fatigue and fever",
    vitals: "Temp 37.8 C",
    allergy: "None recorded",
    nextAction: "Approve CBC report",
    blocker: "Analyzer sync delayed",
    ownerRole: "Lab Technician",
  },
  {
    id: "pj-019",
    visitId: "visit-240530-019",
    token: "INS-007",
    patientName: "Harsh Malhotra",
    uhid: "PLH-241589",
    ageGender: "51 / Male",
    phone: "86******89",
    visitType: "IPD",
    department: "Cardiology",
    doctor: "Dr. Rohan Mehta",
    stage: "Billing Pending",
    location: "Insurance Desk",
    waitingMinutes: 58,
    totalMinutes: 1440,
    priority: "VIP",
    status: "Delayed",
    billingStatus: "Insurance bills",
    labStatus: "Clear",
    radiologyStatus: "Echo ready",
    pharmacyStatus: "Issued",
    insuranceStatus: "Preauthorization pending",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Cardiac package admission",
    vitals: "Stable",
    allergy: "None recorded",
    nextAction: "Upload preauth documents",
    blocker: "Policy document missing",
    ownerRole: "Billing Executive",
  },
  {
    id: "pj-020",
    visitId: "visit-240530-020",
    token: "FUP-012",
    patientName: "Anaya Roy",
    uhid: "PLH-241690",
    ageGender: "5 / Female",
    phone: "85******90",
    visitType: "Follow-up",
    department: "Pediatrics",
    doctor: "Dr. Neha Malik",
    stage: "Registered",
    location: "Reception",
    waitingMinutes: 4,
    totalMinutes: 4,
    priority: "Pediatric",
    status: "Normal",
    billingStatus: "Pending",
    labStatus: "Not ordered",
    radiologyStatus: "Not ordered",
    pharmacyStatus: "Not started",
    insuranceStatus: "Not required",
    dischargeStatus: "Not applicable",
    chiefComplaint: "Vaccination follow-up",
    vitals: "Pending",
    allergy: "Egg allergy",
    nextAction: "Generate token and send to vitals",
    ownerRole: "Receptionist",
  },
];

export const mockJourneyEvents: JourneyEvent[] = [
  { id: "je-001", visitId: "visit-240530-001", time: "09:10 AM", event: "Patient registered", department: "Reception", user: "Front Desk", status: "Completed", duration: "3m" },
  { id: "je-002", visitId: "visit-240530-001", time: "09:13 AM", event: "Token OPD-024 generated", department: "Reception", user: "Front Desk", status: "Completed", duration: "1m" },
  { id: "je-003", visitId: "visit-240530-001", time: "09:18 AM", event: "Vitals captured", department: "Nursing", user: "OPD Nurse", status: "Completed", duration: "6m" },
  { id: "je-004", visitId: "visit-240530-001", time: "09:30 AM", event: "Waiting for doctor", department: "Pediatrics", user: "Queue Desk", status: "Active", duration: "38m" },
  { id: "je-005", visitId: "visit-240530-003", time: "10:05 AM", event: "X-Ray report approved", department: "Radiology", user: "Radiologist", status: "Completed", duration: "42m" },
  { id: "je-006", visitId: "visit-240530-003", time: "10:42 AM", event: "Insurance query raised", department: "Billing", user: "TPA Desk", status: "Blocked", duration: "24m" },
  { id: "je-007", visitId: "visit-240530-004", time: "12:10 PM", event: "Doctor discharge advice", department: "Medicine", user: "Dr. Karan Shah", status: "Completed", duration: "5m" },
  { id: "je-008", visitId: "visit-240530-004", time: "12:35 PM", event: "Final billing pending", department: "Billing", user: "Billing Desk", status: "Blocked", duration: "2h 25m" },
];

export const mockSmartAlerts: SmartAlert[] = [
  { id: "sa-001", type: "Critical Alert", title: "Emergency critical patient waiting for CT", patientId: "pj-002", department: "Emergency / Radiology", age: "7m", severity: "critical", action: "Escalate radiology" },
  { id: "sa-002", type: "Discharge Alert", title: "Discharge blocked by final billing", patientId: "pj-004", department: "Billing", age: "2h 25m", severity: "danger", action: "Notify billing supervisor" },
  { id: "sa-003", type: "Delay Alert", title: "OPD pediatric queue crossed threshold", patientId: "pj-001", department: "Pediatrics", age: "38m", severity: "warning", action: "Call next patient" },
  { id: "sa-004", type: "Insurance Alert", title: "TPA implant query pending approval", patientId: "pj-003", department: "Insurance Desk", age: "24m", severity: "warning", action: "Open claim blocker" },
];

export const mockBottlenecks: BottleneckMetric[] = [
  { id: "bn-001", department: "Billing", delayed: 9, averageWait: "28m", blocker: "Insurance query and final bill verification", trend: "+18%", tone: "danger" },
  { id: "bn-002", department: "Lab", delayed: 7, averageWait: "54m", blocker: "Collection bay overload", trend: "+11%", tone: "warning" },
  { id: "bn-003", department: "Radiology", delayed: 4, averageWait: "41m", blocker: "CT queue pressure", trend: "+8%", tone: "critical" },
  { id: "bn-004", department: "Pharmacy", delayed: 3, averageWait: "17m", blocker: "Stock check and substitute review", trend: "-4%", tone: "info" },
];

export const trackerBoards: TrackerBoard[] = [
  { key: "emergency", route: "/patient-journey/emergency-desk", title: "Emergency Desk", eyebrow: "Patient Journey / Emergency", description: "Triage color, critical timers, unknown patient mode, STAT orders, and ICU/OT handoff.", columns: ["Entry", "Triage", "Vitals", "Doctor", "Stabilize", "Orders", "Admit/OT/ICU"], ownerRoles: ["Doctor", "Nurse", "Receptionist", "Management"] },
  { key: "ipd", route: "/patient-journey/ipd-tracker", title: "IPD Tracker", eyebrow: "Patient Journey / IPD", description: "Admission requests, bed allocation, ward transfer, rounds, nursing tasks, and discharge plan status.", columns: ["Admission Request", "Bed Allocation", "Admitted", "Rounds", "Treatment", "Discharge"], ownerRoles: ["Doctor", "Nurse", "Billing Executive", "Management"] },
  { key: "icu", route: "/patient-journey/icu-command", title: "ICU Command", eyebrow: "Patient Journey / ICU", description: "Vitals trend, critical alerts, ventilator status, medication due, lab critical values, and nurse handover.", columns: ["Critical", "Ventilator", "Review Due", "Medication Due", "Transfer Ready"], ownerRoles: ["Doctor", "Nurse", "Management"] },
  { key: "ot", route: "/patient-journey/ot-tracker", title: "OT Tracker", eyebrow: "Patient Journey / OT", description: "Pre-op checklist, consent, anesthesia clearance, OT room readiness, surgery, recovery, and transfer.", columns: ["Scheduled", "Pre-op", "Consent", "In OT", "Recovery", "Completed"], ownerRoles: ["Doctor", "Nurse", "Billing Executive", "Management"] },
  { key: "lab", route: "/patient-journey/lab-tracker", title: "Lab Tracker", eyebrow: "Patient Journey / Lab", description: "Sample collection, processing, result entry, approval, report readiness, critical values, and TAT delay.", columns: ["Order", "Collection", "Received", "Processing", "Approval", "Ready"], ownerRoles: ["Lab Technician", "Doctor", "Management"] },
  { key: "radiology", route: "/patient-journey/radiology-tracker", title: "Radiology Tracker", eyebrow: "Patient Journey / Radiology", description: "Modality schedule, patient arrival, scan, reporting, approval, readiness, and STAT priority delay.", columns: ["Order", "Scheduled", "Arrived", "Scan", "Reporting", "Ready"], ownerRoles: ["Radiologist", "Doctor", "Management"] },
  { key: "pharmacy", route: "/patient-journey/pharmacy-tracker", title: "Pharmacy Tracker", eyebrow: "Patient Journey / Pharmacy", description: "Prescription payment, stock check, substitute review, picking, dispensing, controlled medicine alerts.", columns: ["Prescription", "Payment", "Stock Check", "Picking", "Substitute", "Dispense"], ownerRoles: ["Pharmacist", "Billing Executive", "Management"] },
  { key: "billing", route: "/patient-journey/billing-tracker", title: "Billing Tracker", eyebrow: "Patient Journey / Billing", description: "Bill requests, service verification, discount, payment, receipt, refund, packages, and clearance.", columns: ["Bill Request", "Verify", "Discount", "Payment", "Receipt", "Clearance"], ownerRoles: ["Billing Executive", "Management"] },
  { key: "insurance", route: "/patient-journey/insurance-tracker", title: "Insurance Tracker", eyebrow: "Patient Journey / Insurance", description: "Pre-authorization, document checklist, approval pending, query raised, claim blockers, and final clearance.", columns: ["Preauth", "Documents", "Query", "Approved", "Claim", "Clearance"], ownerRoles: ["Billing Executive", "Management"] },
  { key: "discharge", route: "/patient-journey/discharge-tracker", title: "Discharge Tracker", eyebrow: "Patient Journey / Discharge", description: "Doctor advice, summary, nursing, pharmacy return, billing, insurance, ready state, and final exit.", columns: ["Advice", "Summary", "Nursing", "Pharmacy", "Billing", "Ready", "Discharged"], ownerRoles: ["Doctor", "Nurse", "Pharmacist", "Billing Executive", "Management"] },
  { key: "followup", route: "/patient-journey/follow-up-tracker", title: "Follow-up Tracker", eyebrow: "Patient Journey / Follow-up", description: "Due today, missed, high-risk, post-surgery, chronic-care, reminder sent, confirmed, and reschedule actions.", columns: ["Due Today", "Reminder", "Confirmed", "Missed", "Reschedule", "Completed"], ownerRoles: ["Receptionist", "Doctor", "Nurse", "Management"] },
];

const radiologyNames = [
  "Aisha Khan",
  "Arjun Kapoor",
  "Meera Joshi",
  "Unknown Emergency",
  "Sofia D'Souza",
  "Nandini Rao",
  "Fatima Sheikh",
  "Rhea Sharma",
  "Harsh Malhotra",
  "Kabir Singh",
  "Leela Menon",
  "Priyanka Bose",
  "Omar Ali",
  "Dev Patel",
  "Tara Gill",
  "Mohan Prasad",
  "Anaya Roy",
  "Ishaan Verma",
  "Rahul Mehta",
  "Ritu Bansal",
];

const radiologyModalities: RadiologyModality[] = ["X-Ray", "CT", "MRI", "USG", "PET", "Mammography"];
const radiologyStatuses: RadiologyOrderStatus[] = ["Ordered", "Payment Pending", "Scheduled", "Arrived", "In Scan", "Reporting", "Approval Pending", "Ready"];
const radiologyPriorities: RadiologyPriority[] = ["Routine", "Urgent", "STAT", "Critical"];
const radiologySources: RadiologySource[] = ["OPD", "IPD", "Emergency"];
const radiologyStudies: Record<RadiologyModality, string[]> = {
  "X-Ray": ["Chest PA", "Ankle AP/Lateral", "Knee AP/Lateral", "Cervical spine"],
  CT: ["CT Brain plain", "CT Chest contrast", "CT Abdomen", "CT Trauma protocol"],
  MRI: ["MRI Brain", "MRI Lumbar spine", "MRI Knee", "MRI Cervical spine"],
  USG: ["USG Abdomen", "USG Obstetric", "USG KUB", "Doppler venous"],
  PET: ["PET CT whole body", "PET cardiac viability"],
  Mammography: ["Bilateral mammography", "Diagnostic mammography"],
};
const radiologyRooms: Record<RadiologyModality, string[]> = {
  "X-Ray": ["X-Ray Room 1", "X-Ray Room 2"],
  CT: ["CT Suite 1", "CT Suite 2"],
  MRI: ["MRI Suite"],
  USG: ["USG Room 1", "USG Room 2"],
  PET: ["PET CT Suite"],
  Mammography: ["Mammo Room"],
};
const radiologists = ["Dr. Kavya Menon", "Dr. Sameer Bhatia", "Dr. Iqbal Khan", "Dr. Ritu Sen"];

function radiologyBlocker(status: RadiologyOrderStatus, priority: RadiologyPriority, index: number) {
  if (priority === "Critical" && status !== "Ready") return "Critical order requires immediate radiologist review.";
  if (status === "Payment Pending") return "Payment or package clearance pending.";
  if (status === "Scheduled" && index % 3 === 0) return "Modality slot running late.";
  if (status === "Reporting" && index % 4 === 0) return "Report draft pending beyond TAT.";
  if (status === "Approval Pending") return "Radiologist approval pending.";
  return undefined;
}

function radiologyNextAction(status: RadiologyOrderStatus) {
  if (status === "Ordered") return "Confirm payment and schedule scan";
  if (status === "Payment Pending") return "Clear payment or package hold";
  if (status === "Scheduled") return "Mark patient arrived";
  if (status === "Arrived") return "Start scan";
  if (status === "In Scan") return "Finish scan and send to reporting";
  if (status === "Reporting") return "Complete report draft";
  if (status === "Approval Pending") return "Approve report";
  return "Notify doctor that report is ready";
}

export const mockRadiologyOrders: RadiologyJourneyOrder[] = Array.from({ length: 50 }, (_, index) => {
  const serial = index + 1;
  const modality = radiologyModalities[index % radiologyModalities.length];
  const status = radiologyStatuses[index % radiologyStatuses.length];
  const source = radiologySources[index % radiologySources.length];
  const priority = index % 11 === 0 ? "Critical" : index % 7 === 0 ? "STAT" : radiologyPriorities[index % radiologyPriorities.length];
  const studyOptions = radiologyStudies[modality];
  const roomOptions = radiologyRooms[modality];
  const waitingMinutes = priority === "Critical" ? 8 + index : 12 + ((index * 7) % 95);
  return {
    id: `rad-order-${String(serial).padStart(3, "0")}`,
    orderNo: `RAD-20260531-${String(serial).padStart(3, "0")}`,
    patientName: radiologyNames[index % radiologyNames.length],
    uhid: source === "Emergency" && index % 5 === 0 ? `UNK-2026-${String(100 + serial).padStart(4, "0")}` : `PLH-${240000 + serial * 17}`,
    ageGender: `${5 + ((index * 7) % 72)} / ${index % 2 ? "Female" : "Male"}`,
    token: `${modality.replace(/[^A-Z]/g, "").slice(0, 3).padEnd(3, "R")}-${String(serial).padStart(3, "0")}`,
    source,
    department: ["Emergency", "Orthopedics", "Neurology", "Medicine", "Pediatrics", "Surgery", "Obstetrics"][index % 7],
    doctor: ["Emergency Team", "Dr. Aman Verma", "Dr. Vikas Sethi", "Dr. Karan Shah", "Dr. Neha Malik", "Dr. Priya Nair"][index % 6],
    modality,
    study: studyOptions[index % studyOptions.length],
    priority,
    status,
    scheduledAt: `31 May 2026, ${String(9 + (index % 9)).padStart(2, "0")}:${index % 2 ? "30" : "00"} ${index % 9 > 3 ? "PM" : "AM"}`,
    waitingMinutes,
    tatMinutes: waitingMinutes + 35 + ((index * 3) % 80),
    room: roomOptions[index % roomOptions.length],
    assignedRadiologist: radiologists[index % radiologists.length],
    billingStatus: source === "Emergency" ? "Emergency hold" : index % 9 === 0 ? "Insurance" : index % 5 === 0 ? "Pending" : index % 4 === 0 ? "Package" : "Paid",
    safetyStatus: ["CT", "MRI"].includes(modality) ? (index % 5 === 0 ? "Pending" : "Completed") : "Not required",
    reportStatus: status === "Ready" ? "Approved" : status === "Approval Pending" ? "Approval pending" : status === "Reporting" ? "Draft" : priority === "Critical" ? "Critical finding" : "Not started",
    blocker: radiologyBlocker(status, priority, index),
    nextAction: radiologyNextAction(status),
  };
});

export const splitWorkflowConfigs: Record<SplitWorkflowKey, SplitWorkflowConfig> = {
  emergency: {
    key: "emergency",
    eyebrow: "Patient Journey / Emergency",
    title: "Emergency Desk",
    description: "High-volume emergency command desk for triage cases, unknown patient mode, critical timers, STAT orders, ICU/OT handoff, and safety blockers.",
    tokenTitle: "Emergency case queue",
    orderTitle: "Emergency action worklist",
    boardColumns: ["Entry", "Triage", "Vitals", "Doctor Assigned", "Stabilizing", "STAT Orders", "Admit/OT/ICU", "Closed"],
    categories: ["Triage", "Vitals", "Doctor Assignment", "STAT Lab", "STAT Radiology", "ICU Bed", "OT Handoff", "Police/MLC"],
    showTokens: true,
  },
  ipd: {
    key: "ipd",
    eyebrow: "Patient Journey / IPD",
    title: "IPD Tracker",
    description: "Admission and ward command desk for admission requests, bed allocation, ward transfer, rounds, nursing care, medication due, orders, and discharge planning.",
    tokenTitle: "Admission and bed queue",
    orderTitle: "IPD care worklist",
    boardColumns: ["Admission Request", "Bed Allocation", "Admitted", "Doctor Round", "Nursing Care", "Orders Pending", "Discharge Plan", "Closed"],
    categories: ["Admission", "Bed Allocation", "Round", "Nursing Task", "Medication", "Diet", "Transfer", "Discharge Plan"],
    showTokens: true,
  },
  icu: {
    key: "icu",
    eyebrow: "Patient Journey / ICU",
    title: "ICU Command",
    description: "Critical care command desk for ICU patients, vitals alerts, ventilator status, medication due, lab critical values, rounds, isolation, and handover.",
    tokenTitle: "ICU critical patient queue",
    orderTitle: "ICU safety worklist",
    boardColumns: ["Critical Alert", "Ventilator Review", "Medication Due", "Lab Critical", "Doctor Review", "Nurse Handover", "Transfer Ready", "Closed"],
    categories: ["Vitals Alert", "Ventilator", "Medication", "Critical Lab", "Fluid Balance", "Isolation", "Doctor Review", "Handover"],
    showTokens: true,
  },
  lab: {
    key: "lab",
    eyebrow: "Patient Journey / Lab",
    title: "Lab Tracker",
    description: "Separate patient token queue from lab order workflow: collection, receipt, processing, result entry, approval, critical alerts, and report readiness.",
    tokenTitle: "Lab token queue",
    orderTitle: "Lab order worklist",
    boardColumns: ["Ordered", "Payment Pending", "Collection Pending", "Collected", "Received", "Processing", "Approval Pending", "Ready"],
    categories: ["Biochemistry", "Hematology", "Microbiology", "Histopathology"],
    showTokens: true,
  },
  radiology: {
    key: "radiology",
    eyebrow: "Patient Journey / Radiology",
    title: "Radiology Tracker",
    description: "Separate scan token queue from radiology order workflow: modality scheduling, arrival, scan, reporting, approval, and readiness.",
    tokenTitle: "Radiology token queue",
    orderTitle: "Radiology order worklist",
    boardColumns: ["Ordered", "Payment Pending", "Scheduled", "Arrived", "In Scan", "Reporting", "Approval Pending", "Ready"],
    categories: ["X-Ray", "CT", "MRI", "USG", "PET", "Mammography"],
    showTokens: true,
  },
  pharmacy: {
    key: "pharmacy",
    eyebrow: "Patient Journey / Pharmacy",
    title: "Pharmacy Tracker",
    description: "Separate patient dispense queue from prescription line workflow: payment check, stock check, picking, substitute review, and dispense.",
    tokenTitle: "Pharmacy token queue",
    orderTitle: "Prescription worklist",
    boardColumns: ["Prescription", "Payment Pending", "Stock Check", "Picking", "Substitute Review", "Ready to Dispense", "Dispensed"],
    categories: ["Medicine", "Controlled Drug", "Consumable", "Substitute"],
    showTokens: true,
  },
  billing: {
    key: "billing",
    eyebrow: "Patient Journey / Billing",
    title: "Billing Tracker",
    description: "Separate counter token queue from bill/service workflow: service verification, discount, payment, refund, package, receipt, and clearance.",
    tokenTitle: "Billing counter queue",
    orderTitle: "Bill and service worklist",
    boardColumns: ["Bill Request", "Verify Services", "Discount Approval", "Payment Pending", "Receipt", "Refund Review", "Clearance"],
    categories: ["OPD Bill", "IPD Bill", "Emergency Bill", "Refund", "Package", "Discount"],
    showTokens: true,
  },
  insurance: {
    key: "insurance",
    eyebrow: "Patient Journey / Insurance",
    title: "Insurance Tracker",
    description: "Claim desk workflow for preauthorization, document checklist, query raised, approved amount, claim blockers, and discharge clearance.",
    tokenTitle: "Insurance desk queue",
    orderTitle: "Preauth and claim worklist",
    boardColumns: ["Preauthorization", "Documents Pending", "Query Raised", "Approval Pending", "Approved", "Claim Blocker", "Final Clearance"],
    categories: ["Preauth", "Document", "Query", "Claim", "Discharge Clearance"],
    showTokens: false,
  },
  discharge: {
    key: "discharge",
    eyebrow: "Patient Journey / Discharge",
    title: "Discharge Tracker",
    description: "Clearance workflow for doctor advice, summary, nursing, pharmacy returns, lab/radiology clearance, billing, insurance, ready, and exit.",
    tokenTitle: "Discharge patient queue",
    orderTitle: "Discharge clearance worklist",
    boardColumns: ["Advice", "Summary", "Nursing", "Pharmacy Return", "Billing", "Insurance", "Ready", "Discharged"],
    categories: ["Summary", "Nursing", "Pharmacy Return", "Billing", "Insurance", "Diagnostics"],
    showTokens: false,
  },
  ot: {
    key: "ot",
    eyebrow: "Patient Journey / OT",
    title: "OT Tracker",
    description: "Surgery case workflow split from readiness tasks: consent, anesthesia, blood, implants, instruments, room readiness, surgery, recovery, transfer.",
    tokenTitle: "OT case queue",
    orderTitle: "Surgery readiness worklist",
    boardColumns: ["Scheduled", "Pre-op Pending", "Consent Pending", "Anesthesia Clearance", "Patient Shifted", "In OT", "Recovery", "Completed"],
    categories: ["Consent", "Anesthesia", "Blood", "Implants", "Instruments", "Room", "Post-op Bed"],
    showTokens: false,
  },
  followup: {
    key: "followup",
    eyebrow: "Patient Journey / Follow-up",
    title: "Follow-up Tracker",
    description: "Follow-up command desk for due today, reminder, confirmed, missed, high-risk, post-surgery, chronic care, reschedule, and completion workflows.",
    tokenTitle: "Follow-up outreach queue",
    orderTitle: "Follow-up action worklist",
    boardColumns: ["Due Today", "Reminder Pending", "Reminder Sent", "Confirmed", "Missed", "High Risk", "Reschedule", "Completed"],
    categories: ["Doctor Follow-up", "Post-surgery", "Chronic Care", "High-risk", "Reminder", "Missed Visit", "Reschedule"],
    showTokens: true,
  },
};

const servicePatients = [
  ["Aisha Khan", "PLH-240221", "12 / Female", "Pediatrics"],
  ["Arjun Kapoor", "PLH-240076", "58 / Male", "Orthopedics"],
  ["Unknown Emergency", "UNK-2026-0098", "35 / Unknown", "Emergency"],
  ["Meera Joshi", "PLH-240188", "42 / Female", "Medicine"],
  ["Sofia D'Souza", "PLH-240402", "27 / Female", "Obstetrics"],
  ["Nandini Rao", "PLH-240516", "64 / Female", "Neurology"],
  ["Fatima Sheikh", "PLH-240623", "71 / Female", "ICU"],
  ["Dev Patel", "PLH-240712", "39 / Male", "Surgery"],
  ["Leela Menon", "PLH-240927", "53 / Female", "Endocrinology"],
  ["Harsh Malhotra", "PLH-241589", "51 / Male", "Cardiology"],
] as const;

const tokenStatuses: ServiceTokenStatus[] = ["Waiting", "Called", "Arrived", "In Service", "On Hold", "Skipped", "Completed"];
const splitPriorities: SplitWorkflowPriority[] = ["Routine", "Urgent", "STAT", "Critical"];

function workflowPrefix(key: SplitWorkflowKey) {
  return key === "emergency" ? "ER" : key === "ipd" ? "IPD" : key === "icu" ? "ICU" : key === "radiology" ? "RAD" : key === "pharmacy" ? "PHR" : key === "billing" ? "BILL" : key === "insurance" ? "INS" : key === "discharge" ? "DIS" : key === "ot" ? "OT" : key === "followup" ? "FUP" : "LAB";
}

function orderItemForWorkflow(key: SplitWorkflowKey, category: string, index: number) {
  const itemMap: Record<SplitWorkflowKey, string[]> = {
    emergency: ["Triage color review", "Fast vitals", "STAT lab order", "STAT radiology order", "Doctor assignment", "ICU bed request", "MLC documentation", "Transfer handoff"],
    ipd: ["Admission verification", "Bed allocation", "Doctor round", "Nursing assessment", "Medication due", "Diet order", "Ward transfer", "Discharge planning"],
    icu: ["Vitals escalation", "Ventilator review", "Medication due", "Critical lab acknowledgment", "Fluid balance review", "Isolation checklist", "Doctor review", "Nurse handover"],
    lab: ["CBC", "CRP", "LFT", "KFT", "Electrolytes", "Blood culture", "HbA1c", "Coagulation profile"],
    radiology: ["Chest X-Ray", "CT Brain", "MRI Brain", "USG Abdomen", "CT Trauma", "Mammography"],
    pharmacy: ["Paracetamol 650", "Pantoprazole 40", "Insulin refill", "Antibiotic course", "Controlled analgesic", "Substitute review"],
    billing: ["Consultation bill", "Lab service verification", "Radiology payment", "Package reconciliation", "Discount approval", "Refund request"],
    insurance: ["Preauth request", "Policy document check", "Query response", "Claim blocker", "Approved amount review", "Final clearance"],
    discharge: ["Summary signature", "Nursing clearance", "Pharmacy return", "Final bill", "Insurance clearance", "Lab/radiology clearance"],
    ot: ["Consent signed", "Anesthesia clearance", "Blood arranged", "Implants available", "Instrument set", "OT room ready", "Post-op bed"],
    followup: ["Reminder call", "WhatsApp reminder", "Doctor follow-up", "Post-surgery checklist", "Chronic care review", "Missed visit callback", "Reschedule confirmation"],
  };
  return `${itemMap[key][index % itemMap[key].length]}${category ? ` - ${category}` : ""}`;
}

export function getSplitWorkflowTokens(key: SplitWorkflowKey): ServiceToken[] {
  const prefix = workflowPrefix(key);
  return Array.from({ length: 50 }, (_, index) => {
    const patient = servicePatients[index % servicePatients.length];
    const priority = index % 13 === 0 ? "Critical" : index % 7 === 0 ? "STAT" : splitPriorities[index % splitPriorities.length];
    const status = tokenStatuses[index % tokenStatuses.length];
    const serial = index + 1;
    return {
      id: `${key}-token-${String(serial).padStart(3, "0")}`,
      tokenNo: `${prefix}-${String(serial).padStart(3, "0")}`,
      patientName: patient[0],
      uhid: patient[1],
      ageGender: patient[2],
      source: index % 9 === 0 ? "Emergency" : index % 5 === 0 ? "IPD" : index % 4 === 0 ? "Follow-up" : "OPD",
      department: patient[3],
      location: key === "emergency" ? "Triage / casualty" : key === "ipd" ? "Admission desk / ward" : key === "icu" ? "ICU bay" : key === "followup" ? "Outreach desk" : key === "ot" ? "Pre-op holding" : key === "billing" ? "Counter queue" : key === "pharmacy" ? "Dispense window" : key === "radiology" ? "Modality waiting" : "Service waiting",
      priority,
      status,
      waitingMinutes: 5 + ((index * 9) % 110),
      linkedOrderIds: [1, 2, 3].slice(0, (index % 3) + 1).map((offset) => `${key}-order-${String(index * 2 + offset).padStart(3, "0")}`),
      nextAction: status === "Waiting" ? "Call token" : status === "Called" ? "Mark arrived" : status === "Arrived" ? "Start service" : status === "In Service" ? "Complete service" : "Review queue status",
      blocker: priority === "Critical" && status !== "Completed" ? "Critical priority waiting beyond target." : index % 11 === 0 ? "Department capacity pressure." : undefined,
    };
  });
}

export function getSplitWorkflowOrders(key: SplitWorkflowKey): ServiceWorkOrder[] {
  const config = splitWorkflowConfigs[key];
  const prefix = workflowPrefix(key);
  return Array.from({ length: key === "lab" || key === "radiology" ? 120 : 80 }, (_, index) => {
    const patient = servicePatients[index % servicePatients.length];
    const category = config.categories[index % config.categories.length];
    const status = config.boardColumns[index % config.boardColumns.length];
    const priority = index % 17 === 0 ? "Critical" : index % 8 === 0 ? "STAT" : splitPriorities[index % splitPriorities.length];
    const serial = index + 1;
    const tokenIndex = (index % 50) + 1;
    return {
      id: `${key}-order-${String(serial).padStart(3, "0")}`,
      orderNo: `${prefix}-ORD-20260531-${String(serial).padStart(3, "0")}`,
      tokenId: `${key}-token-${String(tokenIndex).padStart(3, "0")}`,
      patientName: patient[0],
      uhid: patient[1],
      source: key === "emergency" || index % 9 === 0 ? "Emergency" : key === "ipd" || key === "icu" || index % 5 === 0 ? "IPD" : key === "followup" || index % 4 === 0 ? "Follow-up" : "OPD",
      department: patient[3],
      category,
      item: orderItemForWorkflow(key, category, index),
      priority,
      status,
      owner: key === "emergency" ? "Emergency Team" : key === "ipd" ? "Ward Coordinator" : key === "icu" ? "ICU Nurse" : key === "followup" ? "Follow-up Desk" : key === "lab" ? "Lab Technician" : key === "radiology" ? "Radiologist" : key === "pharmacy" ? "Pharmacist" : key === "billing" || key === "insurance" ? "Billing Executive" : key === "ot" ? "OT Coordinator" : "Discharge Coordinator",
      waitingMinutes: 8 + ((index * 7) % 150),
      tatMinutes: 30 + ((index * 11) % 210),
      billingStatus: index % 6 === 0 ? "Pending" : index % 5 === 0 ? "Package" : index % 9 === 0 ? "Emergency hold" : "Paid",
      safetyStatus: key === "ot" || key === "radiology" ? (index % 5 === 0 ? "Pending" : "Completed") : undefined,
      blocker: priority === "Critical" && status !== config.boardColumns[config.boardColumns.length - 1] ? "Critical item waiting for immediate action." : index % 10 === 0 ? "SLA crossed, supervisor review required." : undefined,
      nextAction: status === config.boardColumns[config.boardColumns.length - 1] ? "Notify next department" : `Move to next ${config.title.toLowerCase()} stage`,
    };
  });
}
